language: node_js
node_js:
  - 0.10
before_script:
  - 'npm install -g karma-cli'
after_script:
  - 'npm install coveralls@2.10.0 && cat ./coverage/*/lcov.info | coveralls'
env:
  global:
    - COVERALLS_SERVICE_NAME="Travis CI"
    - secure: "lU4nF9VnSPV4wqT99h6hTQ+A5RwIyUCFnsgTwXAenRiryi/6aSrSk+nkBaAKLoktMffjJVYwFGpxI28H8fKqNHv87MAYVWlhIzoytmXaOkARMIR4ZXBvH5fDaR65THNHwzTbcUXrj4R/fV1cdN3mg5dx8+rtHOeNE2n47l9DlMk="
